# Generated by Django 4.2.6 on 2023-10-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedIncomeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_before_tax', models.IntegerField()),
                ('tax_deduction', models.IntegerField()),
                ('salary_after_tax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeTaxDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField()),
                ('timeperiod', models.CharField(max_length=10)),
                ('monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_incometax', to='IncomeTaxCalculator.calculatedincometax')),
                ('yearly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_incometax', to='IncomeTaxCalculator.calculatedincometax')),
            ],
        ),
    ]
